version: "3.0"

services:
  bossabox-db:
    container_name: bossabox-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  boosabox-api:
    container_name: bossabox-api
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - bossabox-db
